### ISSUE TITLE
resource.docker_service.task_spec.container_spec.hosts is ignored

### ISSUE THREAD

**Issue by alexkunin** [kreuzwerker/terraform-provider-docker#202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `docker_service`, `docker_container`

### Terraform Configuration Files

Only relevant parts here:
```hcl
provider "docker" {
  host = "ssh://<user@host>"
}

resource "docker_service" "example" {
  task_spec {
    container_spec {
      hosts {
        host = "host.docker.internal"
        ip   = "host-gateway"
      }
    }
  }
}
```

### Expected Behaviour

```
$ docker inspect <container-id>
...
            "ExtraHosts": [
                "host.docker.internal:host-gateway"
            ],
...
```

### Actual Behaviour

No errors or warnings, but resulting service and container do not have any extra host definitions:
```
$ docker inspect <container-id>
...
            "ExtraHosts": null,
...
```

The following workaround works:
```hcl
resource "docker_service" "example" {
  ...
  provisioner "local-exec" {
    command = "ssh <user@host> docker service update ${self.id} --host-add host.docker.internal:host-gateway"
  }
}
```

I've quoted input for `docker_service`, but `docker_container` seems to behave exactly the same. Also, I have tried normal IPv4 also, with same results.

Provider version is 2.11.0, reproducing seems to be trivial, but let me know if you want full/minimal example. Maybe a little help will be needed here in a form of some other minimal example, so I could modify it?

**Comment by alexkunin** [comment]
In addition to the above, after applying mentioned workaround basically all commands (`plan`, `apply`, `destroy`) cause terraform to end prematurely, complaining with tons of errors like this:
```
╷
│ Error: Plugin did not respond
│ 
│   with docker_service.test_2,
│   on test-2.tf line 8, in resource "docker_service" "test_2":
│    8: resource "docker_service" "test_2" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
```
Doing the same command with `TF_LOG=DEBUG` yields the following:
```
2021-05-23T19:56:23.235+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: 2021/05/23 19:56:23 [DEBUG] Docker service inspect: {
2021-05-23T19:56:23.235+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        "ID": "qi3u5tjs8ai20mv2cfbiaqlbk",
2021-05-23T19:56:23.236+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        "Spec": {
...
2021-05-23T19:56:23.236+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:                "TaskTemplate": {
...
2021-05-23T19:56:23.236+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:                                "Hosts": [
2021-05-23T19:56:23.236+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:                                        "host-gateway host.docker.internal"
...
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: PANIC: runtime error: index out of range [1] with length 1
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: 
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: goroutine 261 [running]:
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: github.com/terraform-providers/terraform-provider-docker/docker.flattenServiceHosts(0xc0007f4e80, 0x1, 0x4, 0xb)
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        github.com/terraform-providers/terraform-provider-docker/docker/structures_service.go:286 +0x454
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: github.com/terraform-providers/terraform-provider-docker/docker.flattenContainerSpec(0xc0005fd8c0, 0xc0007c3be0, 0x1, 0x1)
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        github.com/terraform-providers/terraform-provider-docker/docker/structures_service.go:156 +0x771
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: github.com/terraform-providers/terraform-provider-docker/docker.flattenTaskSpec(0xc0005fd8c0, 0x0, 0x0, 0xc0007c3780, 0xc000303620, 0xc00067adc0, 0xc00038efc0, 0x1, 0x4, 0x0, ...)
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        github.com/terraform-providers/terraform-provider-docker/docker/structures_service.go:17 +0x6ab
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: github.com/terraform-providers/terraform-provider-docker/docker.resourceDockerServiceReadRefreshFunc.func1(0xc0006d0f40, 0xc0006d0ea0, 0x2, 0x1, 0xc000768101, 0xc0002beba0)
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        github.com/terraform-providers/terraform-provider-docker/docker/resource_docker_service_funcs.go:153 +0x598
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1(0xc0001a22a0, 0xc0001be380, 0xc0007f4900, 0xc00008c8a0, 0xc00066ae40, 0xc00066ae18)
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/resource/state.go:103 +0x2a4
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0: created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
2021-05-23T19:56:23.238+0300 [DEBUG] provider.terraform-provider-docker_v2.11.0:        github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/resource/state.go:80 +0x1c5
2021-05-23T19:56:23.240+0300 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/kreuzwerker/docker/2.11.0/darwin_amd64/terraform-provider-docker_v2.11.0 pid=24627 error="exit status 2"
```
So, this seems to be a "symmetrical" problem: original issue is "provider ignores service hosts definitions", and this error is something like "provider cannot read existing hosts from service". Let me know if this should be reported as separate issue.

**Comment by tomalok** [comment]
@alexkunin provider version 2.12.0 was recently released -- might want to see if the latest version is also affected.

**Comment by alexkunin** [comment]
Switching to 2.12.0 produced whole bunch of new errors, e.g. this is during `plan` with freshly erased infra:
```
╷
│ Error: Plugin did not respond
│ 
│   with docker_network.internal_network,
│   on traefik.tf line 83, in resource "docker_network" "internal_network":
│   83: resource "docker_network" "internal_network" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-docker_v2.12.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 298 [running]:
github.com/terraform-providers/terraform-provider-docker/internal/provider.resourceDockerServiceStateUpgradeV2(0x1e7fe80, 0xc0000b7dc0, 0xc0000af320, 0x1b03e00, 0xc00064e190, 0xc0000b8a50, 0x1b125c0, 0xc00000f610)
        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_service_migrators.go:26 +0x47f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).upgradeJSONState(0xc0002847b0, 0x1e7fe80, 0xc0000b7dc0, 0x1, 0xc0000af320, 0xc000438000, 0x0, 0xc0003d3aa0, 0x100d7db)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:424 +0xd7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).UpgradeResourceState(0xc0002847b0, 0x1e7fe80, 0xc0000b7dc0, 0xc000489300, 0xc0000b7dc0, 0x100b665, 0x1c28460)
...
Error: The terraform-provider-docker_v2.12.0 plugin crashed!
```
And this is a bit earlier, during `plan` for existing architecture and state (with single change -- new `docker_image` and `docker_service`):
```
2021-05-24T07:59:32.351+0300 [WARN]  Provider "registry.terraform.io/kreuzwerker/docker" produced an invalid plan for docker_network.internal_network, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .ipv6: planned value cty.False for a non-computed attribute
      - .ingress: planned value cty.False for a non-computed attribute
      - .ipam_driver: planned value cty.StringVal("default") for a non-computed attribute
      - .attachable: planned value cty.False for a non-computed attribute
2021-05-24T07:59:32.352+0300 [INFO]  ReferenceTransformer: reference not found: "local.test_2"
...
2021-05-24T07:59:32.359+0300 [DEBUG] provider.terraform-provider-docker_v2.12.0: PANIC: interface conversion: interface {} is nil, not map[string]interface {}
2021-05-24T07:59:32.359+0300 [DEBUG] provider.terraform-provider-docker_v2.12.0: 
2021-05-24T07:59:32.359+0300 [DEBUG] provider.terraform-provider-docker_v2.12.0: goroutine 136 [running]:
2021-05-24T07:59:32.359+0300 [DEBUG] provider.terraform-provider-docker_v2.12.0: github.com/terraform-providers/terraform-provider-docker/internal/provider.resourceDockerServiceStateUpgradeV2(0x1e7fe80, 0xc0000489c0, 0xc000575290, 0x1b03e00, 0xc0004b2090, 0xc00035e210, 0x1b125c0, 0xc0002e81c8)
2021-05-24T07:59:32.359+0300 [DEBUG] provider.terraform-provider-docker_v2.12.0:        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_service_migrators.go:26 +0x47f
```
Results above were achieved with following versions:
```
$ terraform -version
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/kreuzwerker/docker v2.12.0
```
Terraform hinted there was new minor release, so I did an upgrade and tried with latest downloadable version, with basically same results.
```
$ terraform -version
Terraform v0.15.3
# rest is the same
```
These errors do not seem like being related to the original one (at least not on the same level), probably deserve separate issue?

**Comment by mavogel** [comment]
hi @alexkunin thanks for reporting this bug. I already know what it is but I'm surprised that bug happened, as I tried to cover the state upgrade with an empty auth in this [test](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/internal/provider/resource_docker_service_test.go#L21). 

Could you provide your code for the `docker_service`? So I can reproduce it.

**Comment by alexkunin** [comment]
Hey @mavogel, here is minimal `.tf` to reproduce:
```
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.11.0"
    }
  }
}

provider "docker" {
  host = "ssh://docker-swarm-server"
}

resource "docker_service" "example" {
  name = "example"
  task_spec {
    container_spec {
      image = "scratch"
    }
  }
}
```
Some additional info:
* `terraform -v`:
```
Terraform v0.15.4
on darwin_amd64
```
* `docker-swarm-server` -- just an `Ubuntu 20.04.2 LTS` instance with `Docker version 20.10.6, build 8728dd2`, I have passwordless setup in my `~/.ssh/config`, nothing fancy

And steps to reproduce:
1. put the content above into new `main.tf` file within some empty directory
2. do `terraform init`:
```
Initializing the backend...

Initializing provider plugins...
- Finding kreuzwerker/docker versions matching "2.11.0"...
- Installing kreuzwerker/docker v2.11.0...
- Installed kreuzwerker/docker v2.11.0 (self-signed, key ID 24E54F214569A8A5)
...
```
3. do `terraform apply -auto-approve`:
```
# lots of output skipped
Plan: 1 to add, 0 to change, 0 to destroy.
docker_service.example: Creating...
docker_service.example: Creation complete after 5s [id=03vb5mhwes6l8j8z5y1vi847f]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
4. Edit version in `main.tf`:
```
version = "2.12.0"
```
5. do `terraform init -upgrade`:
```
Initializing the backend...

Initializing provider plugins...
- Finding kreuzwerker/docker versions matching "2.12.0"...
- Installing kreuzwerker/docker v2.12.0...
- Installed kreuzwerker/docker v2.12.0 (self-signed, key ID 24E54F214569A8A5)
...
```
6. run any terraform command that involves state, e.g. `terraform plan`:
```
Stack trace from the terraform-provider-docker_v2.12.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 29 [running]:
github.com/terraform-providers/terraform-provider-docker/internal/provider.resourceDockerServiceStateUpgradeV2(0x1e7fe80, 0xc0002553c0, 0xc0000feab0, 0x1b03e00, 0xc0006d1c30, 0xc0000ca4d0, 0x1b125c0, 0xc00000ecc8)
        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_service_migrators.go:26 +0x47f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).upgradeJSONState(0xc00000cf30, 0x1e7fe80, 0xc0002553c0, 0x1, 0xc0000feab0, 0xc00047c000, 0x0, 0xc0005b3aa0, 0x100d7db)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:424 +0xd7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).UpgradeResourceState(0xc00000cf30, 0x1e7fe80, 0xc0002553c0, 0xc000593020, 0xc0002553c0, 0x100b665, 0x1c28460)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:300 +0x2dc
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).UpgradeResourceState(0xc000627e00, 0x1e7ff28, 0xc0002553c0, 0xc0000a49b0, 0xc000627e00, 0xc0000c9e60, 0xc0001d4ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:281 +0xd8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_UpgradeResourceState_Handler(0x1c670e0, 0xc000627e00, 0x1e7ff28, 0xc0000c9e60, 0xc00086b140, 0x0, 0x1e7ff28, 0xc0000c9e60, 0xc0000f8000, 0xa77)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:308 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ffdc0, 0x1e89838, 0xc000082a80, 0xc00025c800, 0xc0001a4bd0, 0x241c7a0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001ffdc0, 0x1e89838, 0xc000082a80, 0xc00025c800, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00009a1f0, 0xc0001ffdc0, 0x1e89838, 0xc000082a80, 0xc00025c800)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-docker_v2.12.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│ 
│   with docker_service.example,
│   on main.tf line 14, in resource "docker_service" "example":
│   14: resource "docker_service" "example" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more
│ details.
╵
```

**Comment by alexkunin** [comment]
And here is some info regarding the original issue. With the following `.tf`:
```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.12.0"
    }
  }
}

provider "docker" {
  host = "ssh://ttn-dev-new"
}

resource "docker_service" "example_service" {
  name = "example_service"
  task_spec {
    container_spec {
      image = "nginx:alpine"
      hosts {
        host = "abc2"
        ip   = "2.2.2.2.2"
      }
      labels {
        label = "bug"
        value = "202"
      }
    }
  }
}

resource "docker_container" "example_container" {
  name  = "example_container"
  image = "nginx:alpine"
  host {
    host = "abc1"
    ip   = "1.1.1.1"
  }
  labels {
    label = "bug"
    value = "202"
  }
}
```
And by using following command to show only relevant parts of `docker inspect` output:
```bash
docker ps --filter label=bug=202 -q | xargs docker inspect | jq '.[] | { Name: .Name, "HostConfig.ExtraHosts": .HostConfig.ExtraHosts }'
```
With versions `2.11.0` and `2.12.0` (tried both, output is the same) of the provider results look like this:
```json
{
  "Name": "/example_service.1.s2qy1kxiy3lkok28l8rncq6j3",
  "HostConfig.ExtraHosts": null
}
{
  "Name": "/example_container",
  "HostConfig.ExtraHosts": [
    "abc1:1.1.1.1"
  ]
}
```
So, apparently standalone container resource gets additional host definitions, while container from service resource does not.
Running `docker service inspect example_service` yields the following (quoting relevant parts):
```json
[
    {
        "Spec": {
            "TaskTemplate": {
                "ContainerSpec": {
                        "abc2:2.2.2.2.2"
                    ],
                },
            },
        },
    }
]
```
You add new host manually like this:
```bash
docker service update example_service --host-add abc3:3.3.3.3
```
Doing `docker service inspect example_service` returns the following (again, quoting only relevant parts):
```json
[
    {
        "Spec": {
            "TaskTemplate": {
                "ContainerSpec": {
                    "Hosts": [
                        "3.3.3.3 abc3"
                    ],
                },
            },
        },
        "PreviousSpec": {
            "TaskTemplate": {
                "ContainerSpec": {
                    "Hosts": [
                        "abc2:2.2.2.2.2"
                    ],
                },
            },
        },
    }
]
```
And inspecting containers with fancy command mentioned above returns correct results:
```json
{
  "Name": "/example_service.1.usjvg7kd8iybhf4irc105wdd9",
  "HostConfig.ExtraHosts": [
    "abc3:3.3.3.3"
  ]
}
{
  "Name": "/example_container",
  "HostConfig.ExtraHosts": [
    "abc1:1.1.1.1"
  ]
}
```
It seems the provider actually passes extra host definitions as they are visible in relevant parts of service spec, but the format is incorrect (switched sides, ":" instead of " " as delimiter). So, should be a trivial fix?

**Comment by alexkunin** [comment]
I don't really know Go or anything, but it seems like host and ip should be swicthed in `flattenServiceHosts`? (https://github.com/kreuzwerker/terraform-provider-docker/pull/205/files#diff-a6e9ddefa84f72a705e97144680ad8914dbe81a5460759061a7eaf706d625b30L292)

Sorry if false alarm.

**Comment by mavogel** [comment]
You're were right :) Just pushed the stuff last evening and this was the missing fix. I also added a comment to #201 to check the properties on the inspect of a container/service that they are properly set to avoid such bugs in the future. Thanks for reporting it 🙏   If you find more stuff in the future don't hesitate to report it.

I will wait for a review and then release a patch

**Comment by alexkunin** [comment]
@mavogel, I have tested same infra config with 2.12.2, seems to work fine, both with IPv4 address and `host-gateway` literal. Thank you!
