### ISSUE TITLE
Plugin crashed when terraform import

### ISSUE THREAD

**Issue by mengzyou** [kreuzwerker/terraform-provider-docker#313]
### Terraform (and docker Provider) Version

```
❯ terraform -v
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.15.0
```

### Affected Resource(s)

* `docker_container`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2.15"
    }
  }
  required_version = ">= 0.14"
}

provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_container" "onedrive" { }
```

### Debug Output

```
❯ terraform import docker_container.onedrive $(docker container inspect --format="{{.ID}}" driveone_onedrive)
docker_container.onedrive: Importing from ID "798fe93ba4bb66f437f7e0d85bba1bd0b8585e2c728d7a6786ec90cd7d6790f0"...
docker_container.onedrive: Import prepared!
  Prepared docker_container for import
docker_container.onedrive: Refreshing state... [id=798fe93ba4bb66f437f7e0d85bba1bd0b8585e2c728d7a6786ec90cd7d6790f0]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
```

### Panic Output

```
Stack trace from the terraform-provider-docker_v2.15.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe69c7e]

goroutine 21 [running]:
github.com/terraform-providers/terraform-provider-docker/internal/provider.getDockerContainerMounts(0xc0004ca000, 0xc00000a1e0, 0x3, 0x4, 0xc00034c000, 0xc0004ce000, 0x0, 0x18ed, 0x207f)
        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_container_structures.go:276 +0x99e
github.com/terraform-providers/terraform-provider-docker/internal/provider.resourceDockerContainerRead(0x12ade50, 0xc0004b2a80, 0xc000587580, 0xf24ec0, 0xc000528a90, 0xc0005d5af0, 0xc000437908, 0x40e0f8)
        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_container_funcs.go:663 +0xeb4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003ac000, 0x12adde0, 0xc00054ecc0, 0xc000587580, 0xf24ec0, 0xc000528a90, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003ac000, 0x12adde0, 0xc00054ecc0, 0xc00050a4d0, 0xf24ec0, 0xc000528a90, 0xc00000faa8, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d5d8, 0x12adde0, 0xc00054ecc0, 0xc00054ed00, 0xc00054ecc0, 0x40b965, 0x1050020)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc00054b540, 0x12ade88, 0xc00054ecc0, 0xc0004b2600, 0xc00054b540, 0xc00055ba10, 0xc000296ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x10917e0, 0xc00054b540, 0x12ade88, 0xc00055ba10, 0xc0004b25a0, 0x0, 0x12ade88, 0xc00055ba10, 0xc000037500, 0x323)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004861c0, 0x12b7718, 0xc000292780, 0xc0004ce100, 0xc0003ea5d0, 0x1866730, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0004861c0, 0x12b7718, 0xc000292780, 0xc0004ce100, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000216180, 0xc0004861c0, 0x12b7718, 0xc000292780, 0xc0004ce100)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-docker_v2.15.0 plugin crashed!
```

### Expected Behaviour

Success to import container state.

### Actual Behaviour

Error: Plugin did not respond

### Steps to Reproduce

1. `terraform import docker_container.onedrive $(docker container inspect --format="{{.ID}}" driveone_onedrive)`

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.

```
Stack trace from the terraform-provider-docker_v2.15.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe69c7e]

goroutine 21 [running]:
github.com/terraform-providers/terraform-provider-docker/internal/provider.getDockerContainerMounts(0xc0004ca000, 0xc00000a1e0, 0x3, 0x4, 0xc00034c000, 0xc0004ce000, 0x0, 0x18ed, 0x207f)
        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_container_structures.go:276 +0x99e
```

https://github.com/kreuzwerker/terraform-provider-docker/blob/v2.15.0/internal/provider/resource_docker_container_structures.go#L276

It seems that `DriverConfig` is `nil`.

**Comment by suzuki-shunsuke** [comment]
I have sent a pull request. https://github.com/kreuzwerker/terraform-provider-docker/pull/315
