### ISSUE TITLE
Plugin does not resopnd when destroying, failure to parse auth header

### ISSUE THREAD

**Issue by ahjones** [kreuzwerker/terraform-provider-docker#375]
I issued a `terraform destroy` command. The Terraform provider failed with the following message

```
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-docker_v2.16.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 81 [running]:
github.com/terraform-providers/terraform-provider-docker/internal/provider.parseAuthHeader({0xc000158000, 0xcf96b1})
        github.com/terraform-providers/terraform-provider-docker/internal/provider/data_source_docker_registry_image.go:198 +0x1a5
github.com/terraform-providers/terraform-provider-docker/internal/provider.deleteDockerRegistryImage({{0xc000572340, 0x32}, {0xc0005724c0, 0x32}, {0xc000572340, 0x16}, {0xc000418760, 0x1e}, {0xc0004b6180, 0x13}, ...}, ...)
        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_registry_image_funcs.go:503 +0x7aa
github.com/terraform-providers/terraform-provider-docker/internal/provider.resourceDockerRegistryImageDelete({0xe19250, 0xc00042e340}, 0x7f8474775108, {0xbab680, 0xc000252db0})
        github.com/terraform-providers/terraform-provider-docker/internal/provider/resource_docker_registry_image_funcs.go:90 +0x285
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc0005c2460, {0xe19250, 0xc00042e340}, 0x24, {0xbab680, 0xc000252db0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:392 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0005c2460, {0xe19250, 0xc00042e340}, 0xc0005b6d00, 0xc0000fa780, {0xbab680, 0xc000252db0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:439 +0x3ab
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000124d38, {0xe19250, 0xc00042e340}, 0xc00041ccd0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000512a80, {0xe192f8, 0xc00047a120}, 0xc000442a80)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xcc05e0, 0xc000512a80}, {0xe192f8, 0xc00047a120}, 0xc00061f080, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013c8c0, {0xe27c18, 0xc0000f6480}, 0xc000178700, 0xc0005fcb70, 0x1381cc0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00013c8c0, {0xe27c18, 0xc0000f6480}, 0xc000178700, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-docker_v2.16.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by suzuki-shunsuke** [comment]
```
github.com/terraform-providers/terraform-provider-docker/internal/provider.parseAuthHeader({0xc000158000, 0xcf96b1})
        github.com/terraform-providers/terraform-provider-docker/internal/provider/data_source_docker_registry_image.go:198 +0x1a5
```

https://github.com/kreuzwerker/terraform-provider-docker/blob/a8517ea3024f681baa609e930120482d09900733/internal/provider/data_source_docker_registry_image.go#L198

**Comment by Junkern** [comment]
@ahjones coud you post your terraform code so that we can better reproduce this issue?

**Comment by Junkern** [comment]
Closing because of inactivity. Will re-open once it happens again and a reproducible case exist.
